on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=0.0.7" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --include-source --output .
    - name: Push
      run: dotnet nuget push Frends.Community.HIT.FileOps.${VERSION}.nupkg --source https://rest.hoglandet.se/nuggets/ --api-key ${HOG_NUGET}
      env:
        HOG_NUGET: ${{ secrets.NUGGET_SECRET }}